import ru.ifmo.rain.mekhanikov.ant2kotlin.dsl.DSLElement
import ru.ifmo.rain.mekhanikov.ant2kotlin.dsl.DSLStringAttributeAdapter
import ru.ifmo.rain.mekhanikov.ant2kotlin.dsl.DSLBooleanAttributeAdapter
import ru.ifmo.rain.mekhanikov.ant2kotlin.dsl.DSLCharAttributeAdapter
import ru.ifmo.rain.mekhanikov.ant2kotlin.dsl.DSLByteAttributeAdapter
import ru.ifmo.rain.mekhanikov.ant2kotlin.dsl.DSLShortAttributeAdapter
import ru.ifmo.rain.mekhanikov.ant2kotlin.dsl.DSLIntAttributeAdapter
import ru.ifmo.rain.mekhanikov.ant2kotlin.dsl.DSLFloatAttributeAdapter
import ru.ifmo.rain.mekhanikov.ant2kotlin.dsl.DSLLongAttributeAdapter
import ru.ifmo.rain.mekhanikov.ant2kotlin.dsl.DSLDoubleAttributeAdapter

class DSLJavac : DSLElement("Javac") {
    var debugLevel: String? by DSLStringAttributeAdapter()
    var source: String? by DSLStringAttributeAdapter()
    var listfiles: Boolean? by DSLBooleanAttributeAdapter()
    var failonerror: Boolean? by DSLBooleanAttributeAdapter()
    var proceed: Boolean? by DSLBooleanAttributeAdapter()
    var deprecation: Boolean? by DSLBooleanAttributeAdapter()
    var memoryInitialSize: String? by DSLStringAttributeAdapter()
    var memoryMaximumSize: String? by DSLStringAttributeAdapter()
    var encoding: String? by DSLStringAttributeAdapter()
    var debug: Boolean? by DSLBooleanAttributeAdapter()
    var optimize: Boolean? by DSLBooleanAttributeAdapter()
    var depend: Boolean? by DSLBooleanAttributeAdapter()
    var verbose: Boolean? by DSLBooleanAttributeAdapter()
    var target: String? by DSLStringAttributeAdapter()
    var includeantruntime: Boolean? by DSLBooleanAttributeAdapter()
    var includejavaruntime: Boolean? by DSLBooleanAttributeAdapter()
    var fork: Boolean? by DSLBooleanAttributeAdapter()
    var executable: String? by DSLStringAttributeAdapter()
    var nowarn: Boolean? by DSLBooleanAttributeAdapter()
    var updatedProperty: String? by DSLStringAttributeAdapter()
    var errorProperty: String? by DSLStringAttributeAdapter()
    var includeDestClasses: Boolean? by DSLBooleanAttributeAdapter()
    var createMissingPackageInfoClass: Boolean? by DSLBooleanAttributeAdapter()
    var compiler: String? by DSLStringAttributeAdapter()
}
